version: '3'

services:
  httpd:
    container_name: httpd
    build: ./docker/httpd
    ports:
      - "80:80"
      - "443: 443"
  tomcat:
    container_name: tomcat
    build: ./docker/tomcat
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./var/log/tomcat:/usr/local/tomcat/logs
    expose:
      - "8009"
